<ImageTransformation>:
    download_button: download_button
    top_id: top_id
    bottom_id: bottom_id
    left_id: left_id
    right_id: right_id
    BoxLayout:
        orientation: 'vertical'

        ActionBar:
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: 'Back'
                    with_previous: False
                    on_release: root.manager.current = 'select_image'
                

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            padding: '5dp'
            spacing: '5dp'

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: '48dp'
                padding: '10dp'
                spacing: '10dp'
                
                BoxLayout:
                    orientation: 'vertical'
                    Label:
                        text: 'Rotation'
                    Slider:
                        id: rotation_slider
                        min: -180
                        max: 180
                        value: 0
                        on_value: root.rotate_image(self.value)

            BoxLayout:
                orientation: 'horizontal'

                TextInput:
                    id: top_id
                    text: "Top pixels"
                    multiline: False
                TextInput:
                    id: bottom_id
                    text: "Bottom pixels"
                    multiline: False
                TextInput:
                    id: left_id
                    text: "Left pixels"
                    multiline: False
                TextInput:
                    id: right_id
                    text: "Right pixels"
                    multiline: False

                Button:
                    text: 'Crop'
                    on_release: root.set_crop_pixels()

        BoxLayout:
            orientation: 'horizontal'
            padding: '10dp'
            spacing: '10dp'
            Image:
                id: map_image
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: None
                width: '180dp'
                padding: '10dp'
                spacing: '10dp'
                BoxLayout:
                    orientation: 'vertical'
                    Label:
                        text: 'CNIG download settings'
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '48dp'
                        padding: '10dp'
                        spacing: '10dp'
                        CheckBox:
                            group: 'resolution'
                            active: True
                            on_active: root.select_resolution(25)
                        Label:
                            text: '25m'
                        CheckBox:
                            group: 'resolution'
                            on_active: root.select_resolution(5)
                        Label:
                            text: '5m'
                        CheckBox:
                            group: 'resolution'
                            on_active: root.select_resolution(2)
                        Label:
                            text: '2m'
                    Button:
                        text: 'Use your own file'
                        on_release: root.use_own_file()
                    Button:
                        id: download_button
                        text: 'Download DEM'
                        on_release: root.download_elevation()
                        disabled: False
                
        BoxLayout:
            size_hint_y: None
            height: '48dp'
            padding: '10dp'
            spacing: '10dp'
            
            Button:
                text: 'Next'
                on_release: root.next_window()
