# select_screen.kv
    #   text: "39.489113, -0.514737"
    #             text: "39.488820, -0.514083"
<SelectScreen>:
    coord1_input: coord1_input_id
    coord2_input: coord2_input_id
    map_image: map_image_id
    # switch: switch_id
    select_image_button: select_image_button_id
    maptiler_checkbox: maptiler_checkbox_id
    google_checkbox: google_checkbox_id
    download_image_button: download_image_button_id

    BoxLayout:
        orientation: 'vertical'

        ActionBar:
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: 'Back'
                    with_previous: False
                    on_release: root.manager.current = 'start_menu'
                   
        GridLayout:
            cols: 4
            size_hint_y: None
            height: 30

            TextInput:
                id: coord1_input_id
                text: ""
                multiline: False

            Button:
                text: 'Paste'
                on_press: root.handle_paste(self, coord1_input_id)

            TextInput:
                id: coord2_input_id
                text: ""
                multiline: False
            Button:
                text: 'Paste'
                on_press: root.handle_paste(self, coord2_input_id)
        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, None

            Label:
                text: 'Search Motor:'
                
            CheckBox:
                id: maptiler_checkbox_id
                group: 'search_motor'
                active: True
                disabled: True
            Label:
                text: 'MapTiler'
            CheckBox:
                id: google_checkbox_id
                group: 'search_motor'
                disabled: True
            Label: 
                text: 'Google'

            Button:
                text: 'Open Map'
                on_press: root.open_map()
            
            # Switch:
            #     id: switch_id
            #     active: True

        Image:
            id: map_image_id
            source: 'img/leaf_icon.png'

        BoxLayout:
            size_hint_y: None
            height: 30

            Button:
                id: select_image_button_id
                text: 'Select Image'
                on_press: root.next_window(self)
                disabled: True

            Button:
                id: download_image_button_id
                text: 'Download Image'
                on_press: root.reload_image(self)
            
            Button:
                text: 'Load Image'
                on_press: root.load_image(self)
#    TextInput:
#                 id: coord1_input_id
#                 text: "39.567191, -2.080372"
#                 multiline: False

#             Button:
#                 text: 'Paste'
#                 on_press: root.handle_paste(self, coord1_input_id)

#             TextInput:
#                 id: coord2_input_id
#                 text: "39.566335, -2.079616"
#                 multiline: False